"""
Shopify → BigQuery sync via dlt (dlt-hub verified source).

Credentials are passed entirely via environment variables — no .dlt/secrets.toml
files are needed, so no extra GitHub Secrets are required beyond what already
exists in the repo.

Environment variables (all sourced from existing GitHub Secrets):
  SHOPIFY_SHOP            – shop subdomain, e.g. "my-store"
  SHOPIFY_CLIENT_ID       – Shopify app client ID  (used to obtain the access token)
  SHOPIFY_CLIENT_SECRET   – Shopify app client secret
  GCP_PROJECT_ID          – GCP project for BigQuery
  GOOGLE_APPLICATION_CREDENTIALS – path to GCP service-account JSON key file
                                   (written by the workflow before this runs)

Optional:
  BACKFILL_START_DATE     – ISO-8601 date/datetime for the earliest data to pull
                             on the very first (or forced) backfill, e.g. "2022-01-01".
                             dlt persists cursor state between runs, so on incremental
                             runs this is ignored and the stored cursor is used instead.
                             Default: "2022-01-01"
"""

import os
import sys

import requests as http_requests

# ---------------------------------------------------------------------------
# Patch the generated shopify_dlt verified source before we import it.
# Newer versions of dlt crash if allow_external_schedulers=True is set but
# Airflow (or interval variables) are not present. This disables that flag
# so it falls back safely to internal incremental state logic.
# ---------------------------------------------------------------------------
shopify_init_path = os.path.join(os.path.dirname(__file__), "shopify_dlt", "__init__.py")
if os.path.exists(shopify_init_path):
    with open(shopify_init_path, "r") as f:
        content = f.read()
    if "allow_external_schedulers=True" in content:
        content = content.replace("allow_external_schedulers=True", "allow_external_schedulers=False")
        with open(shopify_init_path, "w") as f:
            f.write(content)

import dlt
from dlt.common import pendulum
from shopify_dlt import shopify_source  # pulled into repo by: dlt init shopify_dlt bigquery
from shopify_extended import shopify_extended_source
from shopify_segments import shopify_segments_source


# ---------------------------------------------------------------------------
# Streams to sync
# ---------------------------------------------------------------------------
STREAMS = [
    "orders",
    "customers",
    "products",
]


def get_access_token(shop: str, client_id: str, client_secret: str) -> str:
    """Exchange client_id/secret for a fresh Admin API access token.
    Note: The client_credentials grant type is only supported for Shopify Development Stores.
    """
    url = f"https://{shop}.myshopify.com/admin/oauth/access_token"
    payload = {
        "client_id": client_id,
        "client_secret": client_secret,
        "grant_type": "client_credentials"
    }
    resp = http_requests.post(url, data=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()["access_token"]


def main() -> None:
    shop = os.environ["SHOPIFY_SHOP"]
    token = os.getenv("SHOPIFY_ACCESS_TOKEN")
    if not token:
        token = get_access_token(
            shop,
            os.environ["SHOPIFY_CLIENT_ID"],
            os.environ["SHOPIFY_CLIENT_SECRET"],
        )

    shop_url = f"https://{shop}.myshopify.com"

    # BACKFILL_START_DATE is only the initial lower bound.
    # After the first run, dlt's incremental state takes over automatically.
    raw_start = os.environ.get("BACKFILL_START_DATE")
    if not raw_start:
        raw_start = "2026-01-01"
    start_date = pendulum.parse(raw_start)

    # ------------------------------------------------------------------
    # Pipeline definition
    # We pass the credentials explicitly so dlt ignores the placeholder
    # files generated by the `dlt init` command.
    # ------------------------------------------------------------------
    import json
    
    # Load credentials if key file exists, otherwise rely on env config
    credentials = None
    key_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if key_path and os.path.exists(key_path):
        try:
            with open(key_path, "r") as f:
                credentials = json.load(f)
        except Exception:
            pass

    pipeline = dlt.pipeline(
        pipeline_name="shopify_to_bigquery",
        destination=dlt.destinations.bigquery(
            credentials=credentials
        ),
        dataset_name="raw_shopify_gh",
    )

    source = shopify_source(
        private_app_password=token,
        shop_url=shop_url,
        start_date=start_date,
    ).with_resources(*STREAMS)

    extended_source = shopify_extended_source(
        token=token,
        shop_url=shop_url,
    )

    # Segments are GraphQL-only (no date filtering) — skip during REST-only backfills
    # to avoid a redundant full-segment pull on every historical re-run.
    # Set SKIP_SEGMENTS=true in the workflow to suppress.
    skip_segments = os.environ.get("SKIP_SEGMENTS", "").lower() in ("1", "true", "yes")
    all_sources = [source, extended_source]
    if not skip_segments:
        segments_source = shopify_segments_source(token=token, shop_url=shop_url)
        all_sources.append(segments_source)

    print(
        f"Starting dlt sync | shop={shop_url} | start_date={start_date.isoformat()} "
        f"| streams={STREAMS} + extended resources"
        + (" + segments (GraphQL)" if not skip_segments else " [segments skipped]")
    )

    # write_disposition="merge" → dlt UPSERTs rows using the primary key
    # declared in shopify_dlt, so re-running never creates duplicate rows.
    load_info = pipeline.run(all_sources, write_disposition="merge")

    print(load_info)
    print("Sync complete.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"Sync failed: {exc}", file=sys.stderr)
        sys.exit(1)
